### PR TITLE
Catching NICK changes of users.

### PR DESCRIPTION
**Pull request by drobati**
https://github.com/desert-planet/arrakis-hubot/issues/141

Exposed that NICK changes aren't tracked and a user can vote twice.

### CODE REVIEW

**Comment by sshirokov** [comment]
Why did you open this against my fork?

**Comment by drobati** [comment]
A) We may not need this.
B) If you accept this then we could merge it to upstream later if it works for us?

I still need to figure out of the User id changes with nick changes. I think it does?

**Comment by sshirokov** [comment]
> If you accept this then we could merge it to upstream later if it works for us?

I'm not going to accept **anything** to this repo. This is a fork for my work, not a central collaboration point.

Hell, it's super-out of date with the upstream anyway. You should **definitely** work from upstream instead of here.

**Comment by drobati** [comment]
Fair enough but Hayt uses this repo. :+1:

**Comment by sshirokov** [comment]
> Fair enough but Hayt uses this repo.

Because I'm lazy and haven't tested the upstream adapter after I wrote the PR :crying_cat_face:

**Pull request closed without merging**
